<?php

chdir('..');
require_once('init.inc.php');

if (!isset($uuid)) {
    die('Missing UUID parameter.');
}

$q = "SELECT uf.* FROM users u JOIN users_feeds uf ON (u.id = uf.user_id) WHERE u.uuid = ':uuid'";
$feeds = DB::getAll($q, array('uuid' => $uuid));

function xml_entities($string) {
    return strtr(
        $string,
        array(
            "<" => "&lt;",
            ">" => "&gt;",
            '"' => "&quot;",
            "'" => "&apos;",
            "&" => "&amp;",
        )
    );
}

header('Content-type: text/xml; charset=utf-8');
header('Content-Disposition: attachment; filename="subscriptions.xml"');
echo '<?xml version="1.0" encoding="UTF-8"?>';
?>

<opml version="1.0">
    <head>
        <title>OPML Generated by Pocket-RSS</title>
    </head>
    <body>
        <?php foreach ($feeds as $feed): ?>
        <outline text="<?php echo xml_entities($feed->title) ?>" title="<?php echo xml_entities($feed->title) ?>" type="rss" xmlUrl="<?php echo xml_entities($feed->xmlUrl) ?>"/>
        <?php endforeach; ?>
    </body>
</opml>
